### ISSUE TITLE
Multiple trajectories with the same start end clusters

### ISSUE THREAD

**Issue by Leena-Abdullah** [aron0093/cytopath#6]
Hello,

Thank you for building this tool. I just started using it and I am confused about the results I am getting. I am new to python and cytopath so will appreciate all your help!

1. When I plot my trajectories I get 3 different trajectories with the same start and end clusters. Is there a way to resolve them to get just one trajectory? 

2. I am using my seurat clusters for sampling is that okay or should I use louvain clusters?

3. Also, how can I project all my trajectories onto my umap as you did in the paper (Fig1. C.2)?  

5. Also my cell fate probability plot shows that all my cells along the trajectory have the same cell fate probability similar to cytopath_analysis_pancreatic_endocinogenesis.ipynb example when you have not set terminal clusters. What does this mean? 

Thank you!

**Comment by aron0093** [comment]
Hi Leena,

1, You can enforce a single lineage per terminal state by setting the ```cluster_num``` paramater like so ```cytopath.trajectories(adata, cluster_num=1)```

2. In principle this should be fine. The clustering is used to identify distinct terminal states and ideally the terminal region of a lineage would be within a single cluster. You can manually choose clusters by setting ```end_clusters``` parameter in the sampling step with a list of clusters that should be considered terminal states.

3. You can use the plotting function ```cytopath.plot_trajectories(adata, basis='umap')``` If you want to create your own plots, the trajectory coordinates are stored in ```adata.uns['trajectories']['trajectories_coordinates']```

4. Cell fate is computed by normalising the score of each cell towards multiple lineages (i.e. distinct terminal states) It appears that in your case, there is only one lineage and therefore all cells are "fated" to end up in that terminal state.

Hope this helps!

**Comment by Leena-Abdullah** [comment]
Thank you for your reply. This was very helpful. Is there a way to set threshold for end_point and inital_state probabilities to run cytopath on? Like how does cytopath determine the endpoint and startpoint clusters? Does it use a certain threshold of end_point and inital_state probabilities determined by the transition state matrix to define these points?

I am referring to the publication: 'Fate trajectories of CD8+ T cells in chronic LCMV infection'. I am trying to understand how you did the following as mentioned in their methods: 

'Regions with terminal state probability higher than 0.3 were identified and the louvain clusters corresponding to these regions used as start and endpoints'

**Comment by aron0093** [comment]
Yes, you can set the treshholds ```end_point_probability``` and ```root_state_probability```. You can all the details for parameter settings in the doc-string of the ```cytopath.sampling()``` function.

**Comment by Leena-Abdullah** [comment]
Thank you for your answers! 

I have one last concern: 
So cytopath is giving me back 3 end_clusters [1,2,3]. However, when I look at the trajectory it looks like the trajectory line first goes to 1 and then backtracks to 2 and 3. The cell fate probabilities for all the cells in the 3 trajectories is 0.33. So does this mean that cluster 1 is the only true terminal state? When I see the end_point probabilities a few cells in cluster 2 and 3 have a terminal probability close to 1 is that why cytopath is declaring them as terminal states? Most of the cells in cluster 1 have end_point probability close to 1 so I do think that this cluster is the real terminal state. Am I right in my thinking? Also, is there a way to resolve this other than setting cluster 1 as the terminal state?

**Comment by aron0093** [comment]
I would recccomend setting cluster 1 as the end point cluster using the ``end_clusters=[1]``` instead of thresholding the on the end point probability.
